- hosts: 
    - pro-compute01
  tasks:
    - name: install sendmail
      yum: name=sendmail state=installed
#    - name: creat script dir
#      command: mkdir -p /script/multipathcheck
#    - name: push check SCripts
#      copy: src=/jack/multipathMonitor/checkVMDisk.sh  dest=/script/multipathcheck/ mode=777
#    - name: push sendAlertEmailCommand
#      copy: src=/jack/mailCommand/sendAlertEmail.sh dest=/user/sbin/ mode=0777
#    - name: push sendEmailCommand
#      copy: src=/jack/mailCommand/sendEmail dest=/user/sbin/ mode=077 
