---
abstract: 'Loads one of several alternate underlying implementations for a module'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Fatal: 0.006
  Test::More: 0.88
  Test::Requires: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Implementation
requires:
  Carp: 0
  Module::Runtime: 0.012
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Implementation
  homepage: http://metacpan.org/release/Module-Implementation
  repository: git://git.urth.org/Module-Implementation.git
version: 0.07
x_authority: cpan:DROLSKY
