---
abstract: 'Map Perl operating system names to generic types'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0.88
  constant: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-OSType
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Perl::OSType:
    file: lib/Perl/OSType.pm
    version: 1.003
requires:
  Exporter: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/perl-ostype/issues
  homepage: https://metacpan.org/release/Perl-OSType
  repository: git://github.com/dagolden/perl-ostype.git
version: 1.003
x_contributors:
  - 'Jonas B. Nielsen <jonasbn@hoarfrost.local>'
  - 'Paul Green <Paul.Green@stratus.com>'
